version: '3.8'

services:
  app:
    build: ./
    command: python3 manage.py runserver 0.0.0.0:8000 --insecure
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db
    env_file:
      - .env.docker

  db:
    container_name: socks_postgres
    image: postgres
    environment:
      - POSTGRES_DB=${PG_NAME}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    expose:
      - 5432
    volumes:
      - .postgres:/var/lib/postgresql/data
    restart: always

volumes:
  .postgres: null