# Generated by Django 5.1 on 2024-08-20 08:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='menu_field')),
            ],
        ),
        migrations.CreateModel(
            name='Socks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=50)),
                ('name', models.CharField(default='Носки', max_length=50)),
                ('season', models.CharField(choices=[('Зима', 'Зима'), ('Лето', 'Лето')], default='Лето', max_length=4)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('gender', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский'), ('Унисекс', 'Унисекс'), ('Детский', 'Детский')], default='Женский', max_length=7)),
                ('start_image', models.FileField(null=True, upload_to='start_images')),
                ('description', models.TextField(default='не указано')),
            ],
        ),
        migrations.CreateModel(
            name='ImageSocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='socks_gallery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='socks_page.socks')),
            ],
        ),
    ]
