# Generated by Django 5.1.1 on 2024-10-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socks_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socks',
            name='fabric',
            field=models.TextField(default='состав не указан'),
        ),
    ]
