# Generated by Django 4.2.4 on 2024-02-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socks_page', '0002_alter_socks_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='socks',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], default='Женский', max_length=7),
        ),
    ]
