# Generated by Django 4.2.4 on 2024-02-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socks_page', '0003_socks_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socks',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский'), ('Детский', 'Детский')], default='Женский', max_length=7),
        ),
    ]
