# Generated by Django 4.2.4 on 2024-02-22 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socks_page', '0005_imagesocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesocks',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='socks_page.socks'),
        ),
    ]
