# Generated by Django 4.2.4 on 2024-02-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socks_page', '0006_alter_imagesocks_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='socks',
            name='start_image',
            field=models.FileField(null=True, upload_to='start_images'),
        ),
    ]
