name: Deploy to Hosting
on:
  push:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout_repo
        uses: actions/checkout@v4
        
      - name: install pipenv
        run: pip install pipenv

      - name: create requirements.txt
        run: pip freeze > requirements.txt

      - name: pipenv to requirements
        run: pipenv lock -r > requirements.txt

      - name: install dependencies
        run: pipinstall -r requirements.txt

      - name: unit tests
        run: python3 manage.py test
