name: Deploy to Hosting
on:
  push:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout_repo
        uses: actions/checkout@v4

      - name: python 3.11
        run: sudo apt install python3.11
        
      - name: install pipenv
        run: pip install pipenv

      - name: dependencies
        run: pipenv sync

      - name: unit tests
        run: python3 manage.py test
