name: Deploy to Hosting
on:
  push:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout_repo
        uses: actions/checkout@v4

      - name: Install Python, pipenv and Pipfile packages
        uses: wangsha/action-pipenv-setup@main

      - name: unit tests
        run: python3 manage.py test
