name: Deploy to Hosting
on: 
  push:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    
      - name: checkout_repo
        uses: actions/checkout@v4

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: makemigrations
        run: python3 manage.py makemigrations

        env:
          STATICFILES_DIRS: "static"
          MEDIA_ROOT: "media/"
          CSRF_TRUSTED_ORIGINS=https: "https://127.0.0.1"

      - name: migrate
        run: python3 manage.py migrate

        env:
          STATICFILES_DIRS: "static"
          MEDIA_ROOT: "media/"
          CSRF_TRUSTED_ORIGINS=https: "https://127.0.0.1"
          PG_ENGINE: django.db.backends.postgresql
          PG_NAME: Socks
          PG_USER: postgres
          PG_PASSWORD: 1111
          PG_HOST: localhost
          PG_PORT: 5432

      - name: unit tests
        run: python3 manage.py test


