name: Deploy to Hosting
on: 
  push:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout_repo
        uses: actions/checkout@v4

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: makemigrations
        run: python3 manage.py makemigrations
        
      - name: migrate
        run: python3 manage.py migrate
        
      - name: unit tests
        run: python3 manage.py test
